apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: cert-manager
spec:
  destination:
    name: in-cluster
    namespace: cert-manager
  project: system
  source:
    path: cert-manager
    repoURL: https://github.com/crumbhole/kubecog-core
    targetRevision: HEAD
    plugin:
      name: argocd-lovely-plugin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
