apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: ingres-nginx
spec:
  destination:
    name: in-cluster
    namespace: ingress-nginx
  project: system
  source:
    path: ingress-nginx
    repoURL: https://github.com/crumbhole/kubecog-core
    targetRevision: HEAD
    plugin:
      name: kustomize-kubecog
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
