# Change the Vault Address to match yours (base64 encoded)
apiVersion: v1
kind: Secret
metadata:
  name: argocd-vault-replacer-secrets
type: Opaque
data:
  VAULT_ADDR: aHR0cHM6Ly92YXVsdC53b3JsZHByb2dyYW1taW5nLmNvbQ==
