# Downloads the plugin and moves it to /custom-tools, which is then mounted on the argocd-repo-server
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
      - name: argocd-repo-server
        volumeMounts:
        - name: custom-tools
          mountPath: /usr/local/bin/crumblecog-plugin
          subPath: argocd-crumblecog-plugin
      initContainers:
      - name: argocd-crumblecog-plugin-install
        image: ghcr.io/crumbhole/crumblecog-plugin:stable
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools
