apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/external-dns-class: nginx-internal
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: argocd-server-ingress
spec:
  ingressClassName: nginx-internal
  rules:
  - host: argocd.[[ .base.domain.name ]]
    http:
      paths:
      - path: "/"
        pathType: ImplementationSpecific
        backend:
          service:
            name: argocd-server
            port:
              name: https
  tls:
  - hosts:
    - argocd.[[ .base.domain.name ]]
    secretName: argocd-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/external-dns-class: nginx-internal
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
  name: argocd-server-grpc-ingress
spec:
  ingressClassName: nginx-internal
  rules:
  - host: grpc.argocd.[[ .base.domain.name ]]
    http:
      paths:
      - path: "/"
        pathType: ImplementationSpecific
        backend:
          service:
            name: argocd-server
            port:
              name: https
  tls:
  - hosts:
    - grpc.argocd.[[ .base.domain.name ]]
    secretName: argocd-tls-grpc
