apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appofapps-kubecog-core
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: system
  source:
    plugin:
      name: argocd-lovely-plugin
    path: applications
    repoURL: https://github.com/crumbhole/kubecog-core
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
