# Downloads the plugin and moves it to /custom-tools, which is then mounted on the argocd-repo-server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecog-plugin
spec:
  template:
    spec:
      containers:
      - name: argocd-repo-server
        volumeMounts:
        - name: custom-tools
          mountPath: /usr/local/bin/kubecog-plugin
          subPath: kubecog-plugin
        - name: custom-tools
          mountPath: /usr/local/bin/gomplate
          subPath: gomplate
      initContainers:
      - name: kubecog-plugin-install
        image: ghcr.io/crumbhole/kubecog-plugin:stable
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools
