apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: system
spec:
  description: System apps
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources: {}
  sourceRepos:
  - '*'
---
