---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: noreply@crumblecog.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
{{- if eq .platform.dns "cloudflare"}}
          cloudflare:
            email: noreply@crumblecog.com
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-key.txt
{{- end}}
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: noreply@crumblecog.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
{{- if eq .platform.dns "cloudflare"}}
          cloudflare:
            email: noreply@crumblecog.com
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-key.txt
{{- end}}